name: Daily Telegram Bot

on:
  schedule:
    # Run every day at 08:00 Nigeria Time (07:00 UTC)
    - cron: "0 7 * * *"
  workflow_dispatch:  # allows manual run

jobs:
  send_daily_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests schedule

      - name: Run the daily message bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SCHEDULE_TIME: "08:00"
          SEND_ON_START: "true"
        run: |
          python3 New_Age_FxCBot.py
